# Generated by Django 2.0.3 on 2018-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180730_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
