# Generated by Django 2.0.3 on 2018-07-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_review_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company_name',
        ),
    ]
